# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('creatdate', models.DateTimeField()),
                ('fixdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
