# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='auther',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
