# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_essay_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='auther',
        ),
    ]
