# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_essay_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='auther',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
