# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_essay_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='fixdate',
        ),
        migrations.AddField(
            model_name='essay',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='link',
            field=models.CharField(default='https://www.baidu.com/', max_length=2048),
        ),
        migrations.AddField(
            model_name='essay',
            name='platform',
            field=models.CharField(default='网易云音乐', max_length=128),
        ),
        migrations.AlterField(
            model_name='essay',
            name='auther',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='essay',
            name='creatdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
