# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170518_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='link',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='essay',
            name='platform',
            field=models.CharField(max_length=128),
        ),
    ]
