# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170524_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essayid', models.IntegerField()),
                ('user', models.CharField(max_length=128)),
                ('commentcontent', models.CharField(max_length=1024)),
                ('commentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
